language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install maven
  - sudo pip install cpp-coveralls wheel
script:
  - make all
  - make python
  - mvn test -f java/pom.xml
  - make test
  - make test_gcov --always-make
  - python setup.py sdist
  - python setup.py bdist_wheel
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
